# Generated by Django 3.2.4 on 2021-06-23 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3, 'Title must be greater than 3 characters')])),
                ('icon', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4, 'Title must be greater than 4 characters')])),
                ('description', models.TextField()),
                ('demonstration', models.FileField(upload_to='uploads/')),
                ('display', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technology', models.ManyToManyField(to='home.Technology')),
            ],
        ),
    ]
