# Generated by Django 3.2.4 on 2021-06-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_portfolioitem_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='demonstration',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
