# Generated by Django 3.2.4 on 2021-06-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_portfolioitem_demonstration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='technology',
            new_name='technologies',
        ),
    ]
